In [7]:
import pandas as pd
import getpass
from huggingface_hub import notebook_login
import os

from datasets import load_dataset
from fireworks.client import Fireworks
from pydantic import BaseModel, Field
from transformers import AutoTokenizer, AutoModelForCausalLM
import json
from openai import OpenAI

In [8]:
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [9]:
os.environ["FIREWORKS_API_KEY"] = getpass.getpass("fireworks api:")
client = Fireworks(api_key=os.environ["FIREWORKS_API_KEY"])

In [10]:
# sample_data = pd.read_excel('english-danish-openai.xlsx')

# sample_data.to_csv ("english-danish-openai.csv",
#                   index = None,
#                   header=True)

english_danish_sample_data = pd.read_csv('english-danish-openai.csv')
english_danish_sample_data

,English,Danish
0,The cat sat on the windowsill watching the bi...,Katten sad på vindueskarmen og kiggede på fugl...
1,She baked a delicious chocolate cake for her f...,Hun bagte en lækker chokoladekage til sin vens...
2,The new park in the city center has become a p...,Den nye park i byens centrum er blevet et popu...
3,He quickly realized that learning a new langua...,"Han indså hurtigt, at det at lære et nyt sprog..."
4,The old castle on the hill offers a beautiful ...,Det gamle slot på bakken tilbyder en smuk udsi...
...,...,...
114,He enjoyed listening to classical music while ...,"Han nød at lytte til klassisk musik, mens han ..."
115,The old library was filled with countless trea...,Det gamle bibliotek var fyldt med utallige ska...
116,She spent her afternoons tending to her garden.,Hun tilbragte sine eftermiddage med at passe s...
117,The children's laughter echoed in the playground.,Børnenes latter genlød på legepladsen.
118,He captured the beauty of nature through his l...,Han indfangede naturens skønhed gennem sin linse.

In [14]:
instruction = """
          you are an expert translator between English and Danish

          #user will provide you sentences in English 
          #translate users english sentence to Danish.
          #you can only use users english sentence
          
  """

def translate_english_to_danish(english_samples_csv_file, model):
    list_of_danish_sentences = list()
    df = pd.read_csv(english_samples_csv_file)
    for i, row in enumerate(df.iterrows()):
        danish_sentence = client.chat.completions.create(
            model=model,
            messages=[
              {"role": "system", "content": instruction},
              {"role": "user", "content": row[1]['English']}
            ],
        )
        response = danish_sentence.choices[0].message.content
        list_of_danish_sentences.append(response)    
    return list_of_danish_sentences

In [15]:
llama_8b_translation = translate_english_to_danish('./english-danish-openai.csv','accounts/fireworks/models/llama-v3-8b-instruct')

In [16]:
# english_danish_sample_data["Danish_llama_3"] = llama_8b_translation

llama_8b_translation[0]

'Katten sad på vindueskarmen og betragtede fuglene udenfor.'

In [17]:
english_danish_sample_data

,English,Danish
0,The cat sat on the windowsill watching the bi...,Katten sad på vindueskarmen og kiggede på fugl...
1,She baked a delicious chocolate cake for her f...,Hun bagte en lækker chokoladekage til sin vens...
2,The new park in the city center has become a p...,Den nye park i byens centrum er blevet et popu...
3,He quickly realized that learning a new langua...,"Han indså hurtigt, at det at lære et nyt sprog..."
4,The old castle on the hill offers a beautiful ...,Det gamle slot på bakken tilbyder en smuk udsi...
...,...,...
114,He enjoyed listening to classical music while ...,"Han nød at lytte til klassisk musik, mens han ..."
115,The old library was filled with countless trea...,Det gamle bibliotek var fyldt med utallige ska...
116,She spent her afternoons tending to her garden.,Hun tilbragte sine eftermiddage med at passe s...
117,The children's laughter echoed in the playground.,Børnenes latter genlød på legepladsen.
118,He captured the beauty of nature through his l...,Han indfangede naturens skønhed gennem sin linse.

In [18]:
os.environ["OPENAI_API_KEY"] = getpass.getpass("openai api:")


openai_client = OpenAI(
    # This is the default and can be omitted
    api_key=os.environ.get("OPENAI_API_KEY"),
)

In [19]:
# instruction = """
#         you are an expert translator between English and Danish

#         #user will only give you samples of a sentence translated from English to Danish#
#         # Give the translation a score on a scale from one to ten#
#         #format should be something like 'score 1'
#         #Think through your reasoning step-by-step and write the score at the end.#
          
#   """


instruction = """
        you are an expert translator between English and Danish

        #user will only give you samples of a sentence translated from English to Danish#
        # Give the translation a score on a scale from one to ten#
        #format should only be your score          
  """


def evaluate_danish_sentences(english_danish_open_csv, evaluation_sentences):
    scores = list()
    df = pd.read_csv(english_danish_open_csv)
    df["Danish_llama_3"] = evaluation_sentences

    for i, row in enumerate(df.iterrows()): 
        
        response = openai_client.chat.completions.create(
            messages=[
                {"role": "system", "content": instruction},
                {"role": "user", "content": f'''English:{row[1]['English']} 
                                                Danish:{row[1]['Danish_llama_3']}'''}
            ],
            model="gpt-4o",

        )
        try:
            response = response.choices[0].message.content
            #score = int(json.loads(response.split('\n')[-1])['Score'])  
            scores.append(int(response))
        except json.JSONDecodeError as jde:
            continue

    return sum(scores) / len(scores)


llama_8b_avg_score = evaluate_danish_sentences("./english-danish-openai.csv", llama_8b_translation)

In [20]:
f'''For the base model score is {round(llama_8b_avg_score,2)}'''

'For the base model score is 5.98'

In [21]:
!firectl list models

NAME                              CREATE TIME          KIND           CHAT  PUBLIC  STATE  STATUS MESSAGE
755fd9d02a7046ef8368d4a15c86f3cc  2024-07-05 20:10:19  HF_PEFT_ADDON  true  false   READY
83ba6bb9b2ec4ca48bad7e473b87a113  2024-07-05 21:33:24  HF_PEFT_ADDON  true  false   READY
bfa866cd4b4841669796a0deee36d771  2024-06-27 21:36:41  HF_PEFT_ADDON  true  false   READY
c2c7013101774cd19f0a18cc2f109a29  2024-06-27 21:08:19  HF_PEFT_ADDON  true  false   READY

Total size: 4

In [22]:
dataset_id = 'danish-to-english-dataset-v1'
!firectl get dataset {dataset_id}

Name: accounts/m44rkt1-d483d1/datasets/danish-to-english-dataset-v1
Display Name:
Create Time: 2024-07-05 19:45:11
State: READY
Status: OK
Example Count: 119

In [38]:
ft_english_danish_model = '83ba6bb9b2ec4ca48bad7e473b87a113'
full_path_english_danish_model = f'accounts/m44rkt1-d483d1/models/{ft_english_danish_model}'

!firectl get model {ft_english_danish_model}

Name: accounts/m44rkt1-d483d1/models/83ba6bb9b2ec4ca48bad7e473b87a113
Display Name:
Description:
Create Time: 2024-07-05 21:33:24
Created By:
State: READY
Status: OK
Kind: HF_PEFT_ADDON
Deployment Id:
Github Url:
Hugging Face Url:
Peft Details:
  Base Model: accounts/fireworks/models/llama-v3-8b-instruct-hf
  R: 32
  Target Modules: [
    down_proj,
    o_proj,
    v_proj,
    q_proj,
    gate_proj,
    k_proj,
    up_proj
  ]
Public: false
Conversation Config:
  Style: jinja
  System:
  Template:
Context Length: 8192
Supports Image Input: false
Supports Tools: false
Imported From:
Fine Tuning Job: accounts/m44rkt1-d483d1/fineTuningJobs/83ba6bb9b2ec4ca48bad7e473b87a113
Default Draft Model:
Default Draft Token Count: 0
Precisions: []
Deployed Model Refs: []

In [46]:
ft_model_name = f'accounts/m44rkt1-d483d1/models/7e4933e113ae4c1daf02f9ed14c4e416'
base_model_name = "accounts/fireworks/models/llama-v3-8b-instruct"

sample_data = pd.read_csv('english-danish-openai.csv')

sample_data

,English,Danish
0,The cat sat on the windowsill watching the bi...,Katten sad på vindueskarmen og kiggede på fugl...
1,She baked a delicious chocolate cake for her f...,Hun bagte en lækker chokoladekage til sin vens...
2,The new park in the city center has become a p...,Den nye park i byens centrum er blevet et popu...
3,He quickly realized that learning a new langua...,"Han indså hurtigt, at det at lære et nyt sprog..."
4,The old castle on the hill offers a beautiful ...,Det gamle slot på bakken tilbyder en smuk udsi...
...,...,...
114,He enjoyed listening to classical music while ...,"Han nød at lytte til klassisk musik, mens han ..."
115,The old library was filled with countless trea...,Det gamle bibliotek var fyldt med utallige ska...
116,She spent her afternoons tending to her garden.,Hun tilbragte sine eftermiddage med at passe s...
117,The children's laughter echoed in the playground.,Børnenes latter genlød på legepladsen.
118,He captured the beauty of nature through his l...,Han indfangede naturens skønhed gennem sin linse.

In [48]:

def generate_translations(model, english_sentences):
    responses = list()
    for i, sentence in enumerate(english_sentences):
        msg = [
            {"role": "system", "content": 'Translate the English sentence to Danish. Your response must contain ONLY the translated sentence.'},
            {"role": "user", "content": sentence},
        ]
        response = client.chat.completions.create(
            model=model,
            messages=msg,
            temperature=0,
        )

        response = response.choices[0].message.content
        print(response)
        responses.append(response)
    return responses

finetuned_generated_danish = generate_translations(ft_model_name , sample_data['English'].tolist())

finetuned_generated_danish

<|start_header_id|>Katzen sat på vindueskarmen og kiggede på fuglene udenfor.
<|start_header_id|> Hun bagte en lækker chokoladekage til sin vens fødsel.
<|start_header_id|>Den nye park i byens centrum er blevet et populært sted for familier.
<|start_header_id|><|start_header_id|>Han indførte hurtigt, at lære et nyt sprog kræver tålmodighed og praksis.
<|start_header_id|>```
<|start_header_id|>De besluttede at tilbringe deres ferie med at udforske de fjerne øer i Stillehavet.
<|start_header_id|>"Forskeren gjorde en banebrydende opdagelse, der kunne ændre medicinens fremtid."
<|start_header_id|><|start_header_id|>Børnene var begejstrede for at starte deres første skoledag efter somferien.
<|start_header_id|><|start_header_id|>Hun gennemførte maratonen trods de udfordrende vejrforhold.
<|start_header_id|>Den innovative startup har til formål at skabe bæredygtige løsninger til byliv.
<|start_header_id|> Hans bedstefar fortalte ham historier om de gamle dage, da landsbyen var meget mindre.
<|start_header_id|>Duften af friskbrygget kaffe fyldte rummet.
<|start_header_id|><|start_header_id|>Under den stjerneklare himmel lovede de at forblive venskabsfællesskab for evigt.
<|start_header_id|><|start_header_id|>Selvom at det kraftige regnvejr, fortsatte festivalen som planlagt.
<|start_header_id|> Hun beundrede de håndskrevne breve, som hendes bedstemor sendte hende hver måned.
<|start_header_id|><|start_header_id|>Med beslutsomhed han klatrede til toppen af bjerget.
<|start_header_id|>Den lille dreng var fascineret af de farverige fisk i akvariet.
<|start_header_id|><|start_header_id|>Hun tilbragte sine weekender med at arbejde frivilligt på dyreinternatet.
<|start_header_id|>Den unge kunstner udstillede sine malerier i det lokale galleri.
<|start_header_id|><|start_header_id|>De nød en stille picnic ved søen.
<|start_header_id|>Bibliotekaren anbefalede en fantastisk bog om dansk historie.
<|start_header_id|>```
<|start_header_id|><|start_header_id|>Hun øvede klaver hver dag for at forberede sig til sin koncert.
<|start_header_id|>Kysten var fyldt med mennesker, der nød den solrige vejr.
<|start_header_id|><|start_header_id|>Han købte en billet til koncerten, så snart de gik på salg.
<|start_header_id|>〉Børnene byggede et sandslot nær kysten.
<|start_header_id|> Hendes yndlingsbeskæftigelse var at strikke tørklæder til sine venner.
<|start_header_id|><|start_header_id|>De tog en biltur tilbage over hele landet i deres gamle varevogn.
<|start_header_id|>Han åbnede en bageri i sin hjemby efter at have trukket sig tilbage.
<|start_header_id|><|start_header_id|>Filmen fik strålende anmeldelser fra kritikerne.
<|start_header_id|> Hun elskede at udforske de gemte gyder i den gamle by.
<|start_header_id|>De nygifte dansede under stjernene til deres bryllupsfest.
<|start_header_id|><|start_header_id|>Solen gik ned over horisonten og malede himlen i nuancer af lyserød og orange.
<|start_header_id|>Kokken serverede en tre-rettersgourmetmåltid til gæsterne.
<|start_header_id|> Hans drømme var at blive en berømt forfatter en dag.
<|start_header_id|>De gamle ruiner stod som et vidnesmål om en glemt civilisation.
<|start_header_id|> Hun fandt en gammel kort hidden i loftet i sine bedsteforældres hus.
<|start_header_id|>"Festivalen fremviste en række internationale køkkener."
<|start_header_id|><|start_header_id|>Han arbejede utrætteligt for at færdige sit projekt inden for deadline.
<|start_header_id|>〉Børnene lo og legede i de farverige efterårsblade.
<|start_header_id|> Hun barakkerede i en smuk vintagekjole til festen.
<|start_header_id|>Fyreturen ledte skibene trygt til kysten.
<|start_header_id|><|start_header_id|>De adopterede en hvalp fra dyreinternatet i sidste uge.
<|start_header_id|>Haven var fylt med blomstrende blomster af enhver slags.
<|start_header_id|><|start_header_id|>Han begyndte at male som hobby under nedlukningen.
<|start_header_id|>```Koret fremførte en fantastisk tolkning af nationalsangen.```
<|start_header_id|>Hendes bedstemors opskrifter blev givet videre gennem generationer.
<|start_header_id|>Den lille pige var begejret for at se sit yndlingsdyr i zoologisk have.
<|start_header_id|>Boghandlen på hjørnet havde en unik samling af gamle bøger.
<|start_header_id|><|start_header_id|>Han deltog i det årlige maraton for charity.
<|start_header_id|>Kunstnerens vægmaleri oplyste hele gaden.
<|start_header_id|><|start_header_id|>Hun dyrkede yoga hver morgen for at starte sin dag.
<|start_header_id|><|start_header_id|>De nød en billeurige togtur gennem bjergene.
<|start_header_id|>Det lokale bageri er berømt for sine lækre kager.
<|start_header_id|><|start_header_id|>Han skrev et hjerteligt brev til sin gamle ven.
<|start_header_id|>_Byens arkitektur er en blanding af gamle og moderne designs.
<|start_header_id|> Hendes optræden på scenen fik en stående bifald.
<|start_header_id|><|start_header_id|>Han tilbragte weekenden med at reparere sin gamle cykel.
<|start_header_id|>}ildværkeri oplyste nattehimlen under fejringen.
<|start_header_id|>Hun samlede muslingeskaller langs stranden hver sommer.
<|start_header_id|>Den gamle boghandel havde en charmerende og hyggelig atmosfære.
<|start_header_id|>Landmandsmarkedet var fyldt med aktivitet på lørdag morgen.
<|start_header_id|><|start_header_id|>Han holdt en rørende tale til sin søsters bryllup.
<|start_header_id|>Gaderne var dekoreret med farverige lanterner til festivalen.
<|start_header_id|>Hun nødte til at læse romaner i sin fritid.
<|start_header_id|><|start_header_id|>Den gamle ege-træ standset højt i midten af feltet.
<|start_header_id|><|start_header_id|>Han spillede violin med stor dygtighed og lidenskab.
<|start_header_id|><|start_header_id|>Børnene var ivrige efter at flyve deres drager i parken.
<|start_header_id|>} Museet udstillede genstande fra det gamle æra.
<|start_header_id|>Hun elskede at se solnedgangen fra sin altan.
<|start_header_id|>OPSKRIFTEN FØR RETTEN BLEV FORTSATT GYLDIG FRA HENDES BEDSTEFORÆLDER.
<|start_header_id|><|start_header_id|>Floden flød stille gennem den maleriske dal.
<|start_header_id|><|start_header_id|>Han reddede en vild kat og gav den et kærligt hjem.
<|start_header_id|>Velgørenhedsarrangementet indsamlede midler til en god sag.
<|start_header_id|><|start_header_id|>Hun gik i en keramikklasse for at lære en ny færdighed.
<|start_header_id|>Fuglene byggede deres reder højt oppe i træerne.
<|start_header_id|><|start_header_id|>De nødvedlede den fredelige atmosfære på øen.
<|start_header_id|><|start_header_id|>Kokkens kulinariske ekspertise var tydelig i hver ret.
<|start_header_id|> Hun elskede at fange øjeblikke med sin kamera.
<|start_header_id|>Byens natteliv er levende og mangfoldigt.
<|start_header_id|> Hans musik inspirerede mange mennesker verden over.
<|start_header_id|><|start_header_id|>Hun takkede sine værter for deres varme gæstfrihed.
<|start_header_id|><|start_header_id|>De gamle kirkeklokker ringede hver søndag morgen.
<|start_header_id|><|start_header_id|>De fandt et isoleret sted til en stille tilbagetrækning.
<|start_header_id|><|start_header_id|>Han tilbragte timer med at arbejde på sit modeltogssæt.
<|start_header_id|>Den friske duft af fyr fylde luften i skoven.
<|start_header_id|> Hun dansede yndefuldt hen over scenen.
<|start_header_id|>Landsbyggere fejrede høsten med en stor fest.
<|start_header_id|>Han nødte med at vandre i bjergene under sine ferier.
<|start_header_id|>}Billederiet fremstillede en rolig landskab ved daggry.
<|start_header_id|><|start_header_id|>Hun foldede omhyggeligt origami-tranen.
<|start_header_id|>Arkitektens design var både innovativ og funktionelt.
<|start_header_id|>De kiggede på stjerner, mens de lå på tæppet i det åbne felt.
<|start_header_id|>Den lille dreng var begejret for at ride på karrusellen.
<|start_header_id|><|start_header_id|>Hun dedikerede sit liv til at hjælpe dem i nød.
<|start_header_id|><|start_header_id|>Den stille lyd af bølger var beroligende for hendes ører.
<|start_header_id|><|start_header_id|>Han beundrede de gamle biler på den lokale biludstilling.
<|start_header_id|>Hun nødte til at tage lange vandreture i landsbyen.
<|start_header_id|>estivalen fejrede den rige kulturelle arv i regionen.
<|start_header_id|><|start_header_id|>Han fremmede en smuk wooden stol fra bunden.
<|start_header_id|><|start_header_id|>Den lette brise fik blomsterne til at svaje.
<|start_header_id|>Hun havde altid en positiv tilgang til livet.
<|start_header_id|>Museets udstilling om det gamle Egypten var fascinerende.
<|start_header_id|><|start_header_id|>Han spillede fodbold med sine venner hver weekend.
<|start_header_id|>```
<|start_header_id|><|start_header_id|>Han overraskede hende med en buket af hendes yndlingsblomster.
<|start_header_id|>Musikken fra gadeperformerne fyldte luften med glæde.
<|start_header_id|> Hun designede smukke kjoler til det lokale teaters forestillinger.
<|start_header_id|><|start_header_id|>Han nød til at læse poesi på regnfulde eftermiddager.
<|start_header_id|><|start_header_id|>Den varme pejs var indbydende på den kølige aften.
<|start_header_id|> Hun lærte sine børn vigtigheden af venlighed og empati.
<|start_header_id|>```
<|start_header_id|><|start_header_id|>Den unge atlet trænede hver dag til den kommende konkurrence.
<|start_header_id|>Hun malede et vægmaleri på væggen i samfundssenteret.
<|start_header_id|><|start_header_id|>Han nød til at lytte til klassisk musik, mens han arbejdede.
<|start_header_id|>Den gamle bibliotek var fyldt med utallige skatte af viden.
<|start_header_id|><|start_header_id|>Hun tilbragte sine eftermiddage med at passe sin have.
<|start_header_id|>```Børnenes latter gik gennem legepladsen.```
<|start_header_id|>Han indfangede naturens skønhed gennem sin linse.

['<|start_header_id|>Katzen sat på vindueskarmen og kiggede på fuglene udenfor.',
 '<|start_header_id|> Hun bagte en lækker chokoladekage til sin vens fødsel.',
 '<|start_header_id|>Den nye park i byens centrum er blevet et populært sted for familier.',
 '<|start_header_id|><|start_header_id|>Han indførte hurtigt, at lære et nyt sprog kræver tålmodighed og praksis.',
 '<|start_header_id|>```',
 '<|start_header_id|>De besluttede at tilbringe deres ferie med at udforske de fjerne øer i Stillehavet.',
 '<|start_header_id|>"Forskeren gjorde en banebrydende opdagelse, der kunne ændre medicinens fremtid."',
 '<|start_header_id|><|start_header_id|>Børnene var begejstrede for at starte deres første skoledag efter somferien.',
 '<|start_header_id|><|start_header_id|>Hun gennemførte maratonen trods de udfordrende vejrforhold.',
 '<|start_header_id|>Den innovative startup har til formål at skabe bæredygtige løsninger til byliv.',
 '<|start_header_id|> Hans bedstefar fortalte ham historier om de gamle dage, da landsbyen var meget mindre.',
 '<|start_header_id|>Duften af friskbrygget kaffe fyldte rummet.',
 '<|start_header_id|><|start_header_id|>Under den stjerneklare himmel lovede de at forblive venskabsfællesskab for evigt.',
 '<|start_header_id|><|start_header_id|>Selvom at det kraftige regnvejr, fortsatte festivalen som planlagt.',
 '<|start_header_id|>\xa0Hun beundrede de håndskrevne breve, som hendes bedstemor sendte hende hver måned.',
 '<|start_header_id|><|start_header_id|>Med beslutsomhed han klatrede til toppen af bjerget.',
 '<|start_header_id|>Den lille dreng var fascineret af de farverige fisk i akvariet.',
 '<|start_header_id|><|start_header_id|>Hun tilbragte sine weekender med at arbejde frivilligt på dyreinternatet.',
 '<|start_header_id|>Den unge kunstner udstillede sine malerier i det lokale galleri.',
 '<|start_header_id|><|start_header_id|>De nød en stille picnic ved søen.',
 '<|start_header_id|>Bibliotekaren anbefalede en fantastisk bog om dansk historie.',
 '<|start_header_id|>```',
 '<|start_header_id|><|start_header_id|>Hun øvede klaver hver dag for at forberede sig til sin koncert.',
 '<|start_header_id|>Kysten var fyldt med mennesker, der nød den solrige vejr.',
 '<|start_header_id|><|start_header_id|>Han købte en billet til koncerten, så snart de gik på salg.',
 '<|start_header_id|>〉Børnene byggede et sandslot nær kysten.',
 '<|start_header_id|>\xa0Hendes yndlingsbeskæftigelse var at strikke tørklæder til sine venner.',
 '<|start_header_id|><|start_header_id|>De tog en biltur tilbage over hele landet i deres gamle varevogn.',
 '<|start_header_id|>Han åbnede en bageri i sin hjemby efter at have trukket sig tilbage.',
 '<|start_header_id|><|start_header_id|>Filmen fik strålende anmeldelser fra kritikerne.',
 '<|start_header_id|>\xa0Hun elskede at udforske de gemte gyder i den gamle by.',
 '<|start_header_id|>De nygifte dansede under stjernene til deres bryllupsfest.',
 '<|start_header_id|><|start_header_id|>Solen gik ned over horisonten og malede himlen i nuancer af lyserød og orange.',
 '<|start_header_id|>Kokken serverede en tre-rettersgourmetmåltid til gæsterne.',
 '<|start_header_id|>\xa0Hans drømme var at blive en berømt forfatter en dag.',
 '<|start_header_id|>De gamle ruiner stod som et vidnesmål om en glemt civilisation.',
 '<|start_header_id|>\xa0Hun fandt en gammel kort hidden i loftet i sine bedsteforældres hus.',
 '<|start_header_id|>"Festivalen fremviste en række internationale køkkener."',
 '<|start_header_id|><|start_header_id|>Han arbejede utrætteligt for at færdige sit projekt inden for deadline.',
 '<|start_header_id|>〉Børnene lo og legede i de farverige efterårsblade.',
 '<|start_header_id|>\xa0Hun barakkerede i en smuk vintagekjole til festen.',
 '<|start_header_id|>Fyreturen ledte skibene trygt til kysten.',
 '<|start_header_id|><|start_header_id|>De adopterede en hvalp fra dyreinternatet i sidste uge.',
 '<|start_header_id|>Haven var fylt med blomstrende blomster af enhver slags.',
 '<|start_header_id|><|start_header_id|>Han begyndte at male som hobby under nedlukningen.',
 '<|start_header_id|>```Koret fremførte en fantastisk tolkning af nationalsangen.```',
 '<|start_header_id|>Hendes bedstemors opskrifter blev givet videre gennem generationer.',
 '<|start_header_id|>Den lille pige var begejret for at se sit yndlingsdyr i zoologisk have.',
 '<|start_header_id|>Boghandlen på hjørnet havde en unik samling af gamle bøger.',
 '<|start_header_id|><|start_header_id|>Han deltog i det årlige maraton for charity.',
 '<|start_header_id|>Kunstnerens vægmaleri oplyste hele gaden.',
 '<|start_header_id|><|start_header_id|>Hun dyrkede yoga hver morgen for at starte sin dag.',
 '<|start_header_id|><|start_header_id|>De nød en billeurige togtur gennem bjergene.',
 '<|start_header_id|>Det lokale bageri er berømt for sine lækre kager.',
 '<|start_header_id|><|start_header_id|>Han skrev et hjerteligt brev til sin gamle ven.',
 '<|start_header_id|>_Byens arkitektur er en blanding af gamle og moderne designs.',
 '<|start_header_id|>\xa0Hendes optræden på scenen fik en stående bifald.',
 '<|start_header_id|><|start_header_id|>Han tilbragte weekenden med at reparere sin gamle cykel.',
 '<|start_header_id|>}ildværkeri oplyste nattehimlen under fejringen.',
 '<|start_header_id|>Hun samlede muslingeskaller langs stranden hver sommer.',
 '<|start_header_id|>Den gamle boghandel havde en charmerende og hyggelig atmosfære.',
 '<|start_header_id|>Landmandsmarkedet var fyldt med aktivitet på lørdag morgen.',
 '<|start_header_id|><|start_header_id|>Han holdt en rørende tale til sin søsters bryllup.',
 '<|start_header_id|>Gaderne var dekoreret med farverige lanterner til festivalen.',
 '<|start_header_id|>Hun nødte til at læse romaner i sin fritid.',
 '<|start_header_id|><|start_header_id|>Den gamle ege-træ standset højt i midten af feltet.',
 '<|start_header_id|><|start_header_id|>Han spillede violin med stor dygtighed og lidenskab.',
 '<|start_header_id|><|start_header_id|>Børnene var ivrige efter at flyve deres drager i parken.',
 '<|start_header_id|>} Museet udstillede genstande fra det gamle æra.',
 '<|start_header_id|>Hun elskede at se solnedgangen fra sin altan.',
 '<|start_header_id|>OPSKRIFTEN FØR RETTEN BLEV FORTSATT GYLDIG FRA HENDES BEDSTEFORÆLDER.',
 '<|start_header_id|><|start_header_id|>Floden flød stille gennem den maleriske dal.',
 '<|start_header_id|><|start_header_id|>Han reddede en vild kat og gav den et kærligt hjem.',
 '<|start_header_id|>Velgørenhedsarrangementet indsamlede midler til en god sag.',
 '<|start_header_id|><|start_header_id|>Hun gik i en keramikklasse for at lære en ny færdighed.',
 '<|start_header_id|>Fuglene byggede deres reder højt oppe i træerne.',
 '<|start_header_id|><|start_header_id|>De nødvedlede den fredelige atmosfære på øen.',
 '<|start_header_id|><|start_header_id|>Kokkens kulinariske ekspertise var tydelig i hver ret.',
 '<|start_header_id|>\xa0Hun elskede at fange øjeblikke med sin kamera.',
 '<|start_header_id|>Byens natteliv er levende og mangfoldigt.',
 '<|start_header_id|>\xa0Hans musik inspirerede mange mennesker verden over.',
 '<|start_header_id|><|start_header_id|>Hun takkede sine værter for deres varme gæstfrihed.',
 '<|start_header_id|><|start_header_id|>De gamle kirkeklokker ringede hver søndag morgen.',
 '<|start_header_id|><|start_header_id|>De fandt et isoleret sted til en stille tilbagetrækning.',
 '<|start_header_id|><|start_header_id|>Han tilbragte timer med at arbejde på sit modeltogssæt.',
 '<|start_header_id|>Den friske duft af fyr fylde luften i skoven.',
 '<|start_header_id|>\xa0Hun dansede yndefuldt hen over scenen.',
 '<|start_header_id|>Landsbyggere fejrede høsten med en stor fest.',
 '<|start_header_id|>Han nødte med at vandre i bjergene under sine ferier.',
 '<|start_header_id|>}Billederiet fremstillede en rolig landskab ved daggry.',
 '<|start_header_id|><|start_header_id|>Hun foldede omhyggeligt origami-tranen.',
 '<|start_header_id|>Arkitektens design var både innovativ og funktionelt.',
 '<|start_header_id|>De kiggede på stjerner, mens de lå på tæppet i det åbne felt.',
 '<|start_header_id|>Den lille dreng var begejret for at ride på karrusellen.',
 '<|start_header_id|><|start_header_id|>Hun dedikerede sit liv til at hjælpe dem i nød.',
 '<|start_header_id|><|start_header_id|>Den stille lyd af bølger var beroligende for hendes ører.',
 '<|start_header_id|><|start_header_id|>Han beundrede de gamle biler på den lokale biludstilling.',
 '<|start_header_id|>Hun nødte til at tage lange vandreture i landsbyen.',
 '<|start_header_id|>estivalen fejrede den rige kulturelle arv i regionen.',
 '<|start_header_id|><|start_header_id|>Han fremmede en smuk wooden stol fra bunden.',
 '<|start_header_id|><|start_header_id|>Den lette brise fik blomsterne til at svaje.',
 '<|start_header_id|>Hun havde altid en positiv tilgang til livet.',
 '<|start_header_id|>Museets udstilling om det gamle Egypten var fascinerende.',
 '<|start_header_id|><|start_header_id|>Han spillede fodbold med sine venner hver weekend.',
 '<|start_header_id|>```',
 '<|start_header_id|><|start_header_id|>Han overraskede hende med en buket af hendes yndlingsblomster.',
 '<|start_header_id|>Musikken fra gadeperformerne fyldte luften med glæde.',
 '<|start_header_id|>\xa0Hun designede smukke kjoler til det lokale teaters forestillinger.',
 '<|start_header_id|><|start_header_id|>Han nød til at læse poesi på regnfulde eftermiddager.',
 '<|start_header_id|><|start_header_id|>Den varme pejs var indbydende på den kølige aften.',
 '<|start_header_id|>\xa0Hun lærte sine børn vigtigheden af venlighed og empati.',
 '<|start_header_id|>```',
 '<|start_header_id|><|start_header_id|>Den unge atlet trænede hver dag til den kommende konkurrence.',
 '<|start_header_id|>Hun malede et vægmaleri på væggen i samfundssenteret.',
 '<|start_header_id|><|start_header_id|>Han nød til at lytte til klassisk musik, mens han arbejdede.',
 '<|start_header_id|>Den gamle bibliotek var fyldt med utallige skatte af viden.',
 '<|start_header_id|><|start_header_id|>Hun tilbragte sine eftermiddage med at passe sin have.',
 '<|start_header_id|>```Børnenes latter gik gennem legepladsen.```',
 '<|start_header_id|>Han indfangede naturens skønhed gennem sin linse.']

In [49]:
finetuned_generated_danish_avg_score = evaluate_danish_sentences("./english-danish-openai.csv", finetuned_generated_danish)

finetuned_generated_danish_avg_score

7.033613445378151

In [51]:
f'''For the finetuned model score is {round(finetuned_generated_danish_avg_score,2)}'''

'For the finetuned model score is 7.03'